version: "2.1"

services:

  python:
    image: approov/currency-converter-demo
    build: ./server/docker
    restart: always
    env_file: .env
    environment:
      - FLASK_ENV=prod
    networks:
      - traefik
      - default
    command: "flask run -h 0.0.0.0 --reload --port ${HTTP_PORT? Missing value for: HTTP_PORT}"
    volumes:
      - "./server:/home/python/workspace"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${CURRENCY_CONVERTER_DOMAIN? Missing value for: CURRENCY_CONVERTER_DOMAIN}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT}"
      - "traefik.frontend.rule=Host:${CURRENCY_CONVERTER_DOMAIN},report.${CURRENCY_CONVERTER_DOMAIN}"

networks:
  traefik:
    external: true
